-- Current R3 discovery: catalog/configuration only, no application row data.
BEGIN TRANSACTION READ ONLY;
SET LOCAL search_path = public;
SELECT jsonb_build_object(
  'checked_at', now(),
  'gate', (SELECT jsonb_agg(jsonb_build_object('enforcement_state', enforcement_state, 'minimum_contract', minimum_contract)) FROM private.client_contract_config),
  'ledger', (SELECT jsonb_agg(version ORDER BY version) FROM supabase_migrations.schema_migrations WHERE version >= '20260921120000'),
  'hook', (SELECT jsonb_agg(jsonb_build_object('database', d.datname, 'role', r.rolname, 'setting', setting)) FROM pg_db_role_setting s LEFT JOIN pg_database d ON d.oid=s.setdatabase JOIN pg_roles r ON r.oid=s.setrole CROSS JOIN LATERAL unnest(s.setconfig) setting WHERE setting LIKE 'pgrst.db_pre_request=%'),
  'tables', (SELECT jsonb_agg(jsonb_build_object('name', c.relname, 'rls', c.relrowsecurity, 'force_rls', c.relforcerowsecurity, 'owner', pg_get_userbyid(c.relowner), 'acl', c.relacl)) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('comprobante_annulments','customer_account_payment_allocations','parts_used','recurring_expenses','cash_registers','payment_orders')),
  'columns', (SELECT jsonb_agg(jsonb_build_object('table', c.relname, 'column', a.attname, 'acl', a.attacl, 'generated', a.attgenerated, 'authenticated_select', has_column_privilege('authenticated',c.oid,a.attnum,'SELECT'), 'anon_select', has_column_privilege('anon',c.oid,a.attnum,'SELECT'))) FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('comprobante_annulments','customer_account_payment_allocations','parts_used','recurring_expenses','cash_registers','payment_orders') AND a.attnum > 0 AND NOT a.attisdropped),
  'policies', (SELECT jsonb_agg(to_jsonb(p)) FROM pg_policies p WHERE schemaname='public' AND tablename IN ('comprobante_annulments','customer_account_payment_allocations','parts_used','recurring_expenses','cash_registers','payment_orders')),
  'functions', (SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'signature',pg_get_function_identity_arguments(p.oid),'definition',pg_get_functiondef(p.oid),'body_md5',md5(p.prosrc),'definer',p.prosecdef,'acl',p.proacl,'owner',pg_get_userbyid(p.proowner))) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','private') AND p.prokind='f' AND (p.proname IN ('user_can_view_order_amounts','current_user_can_in_business','can_view_inventory_cost','comprobante_is_order_linked','annul_comprobante_atomic','get_payment_allocations','current_user_business_id','is_staff','check_client_contract') OR p.prosrc ~ '(comprobante_annulments|customer_account_payment_allocations|parts_used|recurring_expenses|cash_registers|payment_orders)')),
  'views', (SELECT jsonb_agg(jsonb_build_object('schema',v.schemaname,'name',v.viewname,'definition',v.definition,'options',c.reloptions,'acl',c.relacl,'owner',v.viewowner)) FROM pg_views v JOIN pg_namespace n ON n.nspname=v.schemaname JOIN pg_class c ON c.relnamespace=n.oid AND c.relname=v.viewname WHERE v.schemaname IN ('public','private') AND v.definition ~ '(comprobante_annulments|customer_account_payment_allocations|parts_used|recurring_expenses|cash_registers|payment_orders)')
) AS discovery;
ROLLBACK;
