-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20240411
-- Original remote name: add_arca_parametros_table
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.