-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260427170537
-- Original remote name: add_mayorista_fields
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.