-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260504212425
-- Original remote name: fix_duplicate_indexes_and_add_fk_indexes
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.