-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260419203805
-- Original remote name: grant_business_users_view_permissions
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.