-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260427213909
-- Original remote name: add_sale_type_to_finance_entries
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.