-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260505210829
-- Original remote name: cuentas_corrientes_module
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.