-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512220729
-- Original remote name: create_get_business_subscription_features
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.