-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260622195821
-- Original remote name: whatsapp_vault_credentials
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.