-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512225712
-- Original remote name: subscription_payments_v3
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.