-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260427164004
-- Original remote name: create_recurring_expenses
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.