-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260418143535
-- Original remote name: harden_all_functions_search_path
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.