-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260623120000
-- Original remote name: billing_stageC_admin_roles_audit
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.