-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510193644
-- Original remote name: add_logo_url_to_businesses
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.