-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260505201306
-- Original remote name: tasks_module_completo
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.