-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260520231152
-- Original remote name: fix_recurring_expenses_grants_and_policies
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.