-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260419203055
-- Original remote name: add_permissions_to_profiles
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.