-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260521210801
-- Original remote name: fix_credit_note_finance_reversal
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.