-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260520124132
-- Original remote name: fix_dollar_price_sync_rpc
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.