-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260504212359
-- Original remote name: fix_rls_auth_uid_initplan
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.