-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260622132235
-- Original remote name: whatsapp_rls_hardening
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.