-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260514133656
-- Original remote name: storage_business_assets_select_policy
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.