-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260516144112
-- Original remote name: atomic_supplier_balance_trigger_and_pos_indexes
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.