-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260507143655
-- Original remote name: wholesale_customer_type_and_price_tracking
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.