-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260516143422
-- Original remote name: fix_financial_data_orphans_and_constraints
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.