-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260413212744
-- Original remote name: add_order_print_settings_to_business_settings
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.