-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512152921
-- Original remote name: fix_comprobante_item_golden_armor_privacy
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.