-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260522135429
-- Original remote name: add_normalized_name_triggers
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.