-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260418143736
-- Original remote name: fix_security_definer_views_and_bucket_listing
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.