-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260505123456
-- Original remote name: fix_trigger_expense_finance_skip_factura
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.