-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260516142450
-- Original remote name: fix_adjust_stock_on_order_item_created_by
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.