-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260514152510
-- Original remote name: system_admins_add_user_id
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.