-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260508154831
-- Original remote name: fix_demo_user_password_cost
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.