-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510202415
-- Original remote name: fix_portal_rls_business_isolation
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.