-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260418141948
-- Original remote name: grant_warranties_privileges
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.