-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510211023
-- Original remote name: merge_portal_to_mi_negocio_v2
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.