-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510185040
-- Original remote name: grant_anon_businesses_portal_read
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.