-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512234751
-- Original remote name: mark_existing_businesses_onboarding_complete
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.