-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260626174811
-- Original remote name: owner_system_owner_activation
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.