-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260415143243
-- Original remote name: grant_cash_registers_financial_movements
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.