-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260413203933
-- Original remote name: grant_tasks_to_authenticated
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.