-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260516142508
-- Original remote name: cleanup_duplicate_triggers_and_orphan_functions
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.