-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260506130522
-- Original remote name: cajas_add_difference
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.