-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512221106
-- Original remote name: subscription_security_enforcement
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.