-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260526133633
-- Original remote name: fix_supplier_account_movement_trigger_coalesce
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.