-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260515135131
-- Original remote name: product_variants_and_parent_id
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.