-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260512154807
-- Original remote name: fix_stock_repair_rpcs_include_borrador_v2
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.