-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260508154356
-- Original remote name: seed_demo_portal_user
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.