-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260508124109
-- Original remote name: repair_financial_movements_metodo_pago
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.