-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260520223947
-- Original remote name: personal_recurring_expenses_module
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.