-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510203722
-- Original remote name: fix_rls_drop_public_select_policies
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.