-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260417132543
-- Original remote name: arca_config_missing_columns
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.