-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260508124056
-- Original remote name: fix_caja_payment_trigger_metodo_pago
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.