-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510184416
-- Original remote name: businesses_portal_public_read
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.