-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260506190924
-- Original remote name: audit2_order_items_movements_and_income_dedup
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.