-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260427215932
-- Original remote name: add_mayorista_enabled_to_business_settings
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.