-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260521125737
-- Original remote name: add_cliente_paga_repuesto_to_order_parts
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.