-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260413205637
-- Original remote name: create_inventory_valuation_history
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.