-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260521231208
-- Original remote name: supplier_atomic_rpcs_v1
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.