-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260526135759
-- Original remote name: fix_supplier_rpc_movement_type_constraint
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.