-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260515130417
-- Original remote name: inventory_extended_fields
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.