-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510181632
-- Original remote name: inventory_portal_catalog_columns
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.