-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260510190314
-- Original remote name: clic_wholesale_product_settings
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.