-- HISTORICAL MIGRATION MARKER â€” NO-OP
-- Remote version: 20260419183500
-- Original remote name: create_order_items_system
-- This migration was executed historically in production.
-- Its SQL is represented by the verified baseline 20260628190324.
-- Do not add executable SQL to this file.